// REMINDER: TO PAUSE A FUNCTION DO setTimeout(s)

// instead just make a value 
// base value is 3 seconds

/* generate number between 0 and one and divide it by 

1 / generated num

That will be the CRNG, in which will add to TRNG.



if (CRNG > BRNG) BRNG = CRNG


*/


var setCRNG = new Decimal(0)
const Roll = {
  cooldown: 5,
  baseCoolDown: 5,
  rollTime: 3,
  Amount: 0,
  trueVal: 0
}
 
var RawRNG = 1;
var simulated = []

//const text = ``

//i'd probably need this for TQET
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function animateArray(arr) {
  let pritArr = []
  let slowDown = 1

  for (x in arr) {
    text = arr[x] 
    
    pritArr.push(1 / arr[x]) 

    RawRNG = x != (arr.length - 1) ? arr[x] + " [!]" : arr[x]
    await delay(100 + ((25 * Roll.baseCoolDown) * slowDown))
    slowDown += 1
    
   
    //for technical stuff
  }

  Roll.trueVal = 1/arr[x]
  // 

  console.log(pritArr)
  if (player.Sol.TRNG && player.Sol.CRNG) player.Sol.TRNG = player.Sol.TRNG.plus(player.Sol.CRNG)

  simulated = []
 
}

async function opacitizeArray(arr, ext=[]) {
  for (x in arr) {
    arr += `${arr[x]} \n<br>` + ext ? ext : ""
    await delay(1500)
  };
}  
//TMSQoL , TRMQoL , TBSQoL
const TMSQoL = [
   `Plasmate/Multiply is no longer reset on Convertary<br>`,
   `You now generate 10% of eclipsium gain per second<br>`,
   `Entering check upgrades no longer resets Multiply<br>`
]
const TRMQoL = [
    `Plasmate/Multiply is no longer reset on Centralize<br>`,
    `Automate Phaser, it does not spend resources<br>`,
    `Solarizer Content is no longer reset on check entering.<br>`
]
const TBSQoL = [
    `All Solarize Upgrades are kept on layer 2 resets<br>`,
    `Solar light generation can now be generated by ^0.2 of Generation gains<br>`,
    `Start generating Lunar essence of ^0.5 of it's gains<br>`,
]
const TBCQoL = [
    `Centralizing no longer roots Solar Shards.<br>`,
    `Effector tiers are no longer reset on Lunar and Solar Resets<br>`,
    `You're Ready... <br><br> Unlock Solar bursting.<br> (also +10 to multiply's bulk purchasing)`
]
/*
  SETTINGS
  for later
  random: completely randomized, how meta!
  slowDown: for suspense...

  */
function roll() {
    Roll.cooldown = Roll.baseCoolDown

    simulated = [Math.random(),Math.random(),Math.random(),Math.random(),Math.random(),Math.random()]
    RawRNG = simulated[simulated.length]
    return animateArray(simulated);
  
}
/*
  SETTINGS
  for later
  random: completely randomized, how meta!
  slowDown: for suspense...
*/
const MNGStyle = {
  "width": "180px",
  "height": "150px",
  "border-radius": "0px",
  "border": "0px",
  "margin": "0px",
  "text-shadow": "0px 0px 10px rgb(157, 122, 48)",
}

const Tier2QueuedUpgs = {
  "width": "250px",
  "height": "144px",
  "border-radius": "0px",
  "border": "0px",
  "margin": "2px",
  "text-shadow": "1px 1px 10px #ffa500",
  "color": "#000000"
}
const SolarisDialogue = [
      "So… you made it, it’s about time that you came",
      "Not like i have been watching you and all…",
      "And i have watched you… being resourceful with Lunaris… <br>",
      "...Enough chit chat, lets get to the point.",
      "You will prove your worth to me, Solaris, The Solar God.",
      "I will reward you with something much better. The power of the sun.",
      "But first… you have to prove that you are ready for this power.",
      "I will reward you well. do not melt with with the force of the suns.",
  ]
addLayer("Sol", {
    symbol() {return `<p><img src="resources/Solaris.png" style="width:80px;height:80px;"></p>`},
    startData() { return {
        unlocked: true,

        Aperativity: new Decimal(0),
        Aperature: new Decimal(0),
        CPBoost: new Decimal(0),
   
        TRNG: new Decimal(0),
        BRNG: new Decimal(1),
        SRNG: new Decimal(0), //stored RNG?
      
        CRNG: new Decimal(0),
        Amount: Roll.Amount,

        MNG: {        
          Replic: 0,
          Smare: 0,
          Total: new Decimal(0),
          Quantify: new Decimal(0),
          Elevate: new Decimal(0), 
        },

        TMSun:{ 
          x: new Decimal(0)
        },
        TRMoon: {
          x: new Decimal(0)
        },
        TBSun: {
          x: new Decimal(0)
        },
        TBCore: {
          x: new Decimal(0)
        },

     
      

        tab: "",
        sub: "",
        activeCheck: "",

        solarBurst: false, //should move base Solarity cap to 1e1000, for Pestillessence
        Heliosphere: false,
    }},
    color: "#612700",
   // Can be a function that takes requirement increases into account
   

  
   update(diff) {

                // rebalance this effect
   player["Sol"].CPBoost = player["Sol"].Aperativity.clampMin(1).log(10)




   if (Roll.cooldown > 0) Roll.cooldown = Roll.cooldown - 1 * diff
    
   if (player.Sol.MNG.Rans >= 1) Roll.baseCoolDown = 5 / (1.06 ** player.Sol.MNG.Rans)

   player.Sol.MNG.Total = new Decimal(player.Sol.MNG.Rans + player.Sol.MNG.Replic).add(player.Sol.MNG.Quantify).add(player.Sol.MNG.Elevate)

  }, 
  
  
      
  
  
  
  
  
  
  
  tabFormat: {
    "": {      
      content: [     

      ["row", [ //check upgrades
          ["Custom", {id:11}],
          ["Custom", {id:12}],
          ["Custom", {id:13}],
        ]],
      ["row", [ //check upgrades
          ["Custom", {id:21}],
          ["Custom", {id:22}],
        ]],
        "blank",        
      ["Viewer",  {id:11, title: "Aparature Stats"}],
      ["Reset", {id:11, title: "Aperaturize"}],      
      "blank", "blank", 
      ["display-text", function() { 
        if (player.Sol.tab == 'Aparal' )
         return `Remember: Queued upgrades forces a recontrol reset<br>
        Since these are Tier II Queued upgrades, these also reset Light and Dark, and roots Lunar power by 5
        `
      }],
"blank", "blank", 
      ["row", [ //check upgrades
        ["upgrade",11],
        ["upgrade",12],  
      ]],    
      ["row", [ //check upgrades
        ["upgrade",13],
        ["upgrade",14],  
      ]],
  // #reigion Randomizor
      ["row", [ //check upgrades
        ["Viewer",  {id:12, title: "BRNG Milestones"}],
        ["Viewer",  {id:13, title: "-----[ Machine ]-----"}],
        ["Viewer",  {id:14, title: "TRNG Milestones"}],
      ]],

      ["row", [ //check upgrades
        ["clickable",11],
        ["clickable",12],  
      ]],

      ["row", [ //check upgrades
        ["clickable",21],
        ["clickable",22],  
      ]],

  // #endregion

],},},


    //for unlockable content 
  Custom: {
    11: {
      display() {return `<h2>Aparalitize</h2>`},
      onClick() {player.Sol.tab = "Aparal"; player.Sol.sub = ""},
      canClick() {return true},
      style() {return {
        "width": "100px",
        "height": "40px",
        }},  
      unlocked() {return true}
    },
    12: {
      display() {return `<h2>The Randomizor</h2>`},
      onClick() {player.Sol.tab = "RNG"},
      canClick() {return true},
      style() {return {
        "width": "130px",
        "height": "40px",
        }},  
      unlocked() {return hasUpgrade("Sol",14) || player.Sol.CRNG.gt(1)}
    },
    13: {
      display() {return `<h2>The Core</h2>`},
      onClick() {player.Sol.tab = "Core"},
      canClick() {return true},
      style() {return {
        "width": "130px",
        "height": "40px",
        }},  
      unlocked() {return player.Sol.MNG.Total.gte(32)}
    },

    21: {
      display() {return `<h3>Sub: Wall Of Checks </h3>`},
      onClick() {if (player.Sol.tab == "Core") player.Sol.sub = "WoC"},
      canClick() {return false},
      style() {return {
        "width": "120px",
        "height": "40px",
        }},  
      unlocked() {return player.Sol.TRNG.gte(1e10) && player.Sol.tab == "Core"}
    },
    22: {
      display() {return `<h3>Sub: Solar Bursting </h3>`},
      onClick() {if (player.Sol.tab == "Core") player.Sol.sub = "Bursting"},
      canClick() {return true},
      style() {return {
        "width": "100px",
        "height": "40px",
        }},  
      unlocked() {return player.Sol.TBCore.x.gte(3) && player.Sol.tab == "Core"},
    },
 
// the UI thing
111: {
  display() {
    let short = ""
    if (player.Sol.selected == "TMSun") short = `TMS`
    else if (player.Sol.selected == "TRMoon") short = `TRM`
    else if (player.Sol.selected == "TBSun") short = `TBE`
  }
},

112: {
  display() {

    let TRMoonReq = player.Sol["TRMoon"].active ? new Decimal(47).sub(player.Sol["TRMoon"].pending.mul(3.5).round()) : 30
    let TBEclReq = player.Sol["TBSun"].active ? new Decimal("5e430").div(player.Sol["TBSun"].pending.pow_base(1e15)) : 40
    let TMSunReq = player.Sol["TMSun"].active ? new Decimal(1200).mul(player.Sol["TMSun"].pending.pow_base(3.1111).round()) : 40



    if (!Selecting("active")) return `<h2>Begin studying the celestial bodies...</h2>`
    else {
      if (player.C.CenterPoints.lt(TRMoonReq) && player.Sol["TRMoon"].active) return `<h2>Goal: ${TRMoonReq} Center points </h2>`
      else if (player.points.lt(TBEclReq) && player.Sol["TBSun"].active) return `<h2>Goal: ${format(TBEclReq)} Solarity </h2>`
      else if (player.GL.Solar_Shards.lt(TMSunReq) && player.Sol["TMSun"].active) return `<h2>Goal: ${format(TMSunReq)} Solar Shards </h2>`
      else return `<h2> Deem yourself knowledgeable...? </h2>`
    }
  },
  onClick() { 
    //Increase only if met requirements  

    let TRMoonReq = player.Sol["TRMoon"].active ? new Decimal(47).sub(player.Sol["TRMoon"].pending.sub(1).mul(3.5).round()) : 30
    let TBSunReq = player.Sol["TBSun"].active ? new Decimal("5e430").div(player.Sol["TBSun"].pending.sub(1).pow_base(1e15)) : 40
    let TMSunReq = player.Sol["TMSun"].active ? new Decimal(1200).mul(player.Sol["TMSun"].pending.pow_base(3.1111).round()) : 40

    //Increase Melted sun requirements
    /*
    player.Sol[player.Sol.selected].active = true; layer2Reset()
    */

    //The Broken Core clear  
  if (tmp["Sol"].Custom["112"].canClick && player.Sol["TBCore"].active) {
      if (player.Sol["TBCore"].pending.eq(3)) doPopup("msg","...H-How~ What did you do…!? h-he wont like this...", "Solaris:",10) /* ...H-How~ What did you do… */
      else if (player.Sol["TBCore"].pending.eq(2)) doPopup("msg","You should probably give up at this point…", "Solaris:",10) 
      else if (player.Sol["TBCore"].pending.eq(1)) doPopup("msg","so… hows it going? Feeling the pain yet? It only gets worse from here…", "Solaris:",10)   
   }
    
    // if player can complete the check
      // The Raging Moon clear
    if (player.C.CenterPoints.gte(TRMoonReq) && Selecting("pending").gte(1) && player.Sol["TRMoon"].active) 
    {
      player.Sol[player.Sol.selected].x = player.Sol[player.Sol.selected].pending 
      player.Sol[player.Sol.selected].active = false
      player.Sol[player.Sol.selected].pending = new Decimal(0)
      player.Sol.selected = ""

    } 
      // The Bleeding Eclipse clear
    else if (player.points.gte(TBSunReq) && Selecting("pending").gte(1) && player.Sol["TBSun"].active) 
    {
      player.Sol[player.Sol.selected].x = player.Sol[player.Sol.selected].pending 
      player.Sol[player.Sol.selected].active = false
      player.Sol[player.Sol.selected].pending = new Decimal(0)
      player.Sol.selected = ""

    } 
      // The Melted Sun clear
    else if (player.GL.Solar_Shards.gte(TMSunReq) && Selecting("pending").gte(1) && player.Sol["TMSun"].active) {
      player.Sol["TMSun"].x = player.Sol["TMSun"].pending 
      player.Sol[player.Sol.selected].active = false
      player.Sol[player.Sol.selected].pending = new Decimal(0)
      player.Sol.selected = ""

    }

    //else quit the check
    else if (Selecting("active")) {
      let canLeave = false
      if (player.C.CenterPoints.gte(TRMoonReq) && player.Sol["TRMoon"].active) canLeave = true
      else if (player.points.gte(TBSunReq) && player.Sol["TBSun"].active) canLeave = true
      else if (player.GL.Solar_Shards.gte(TMSunReq) && player.Sol["TMSun"].active) canLeave = true


    if (Selecting("pending").gte(1) && Selecting("x").lte(0) && canLeave) {alert("Make sure to read the guide before entering a check!"); }
      player.Sol[player.Sol.selected].active = false
      player.Sol.selected = ""
     // player.Sol[player.Sol.selected] = ""
      return;
    }
    
    //start the Check thing
  if (Selecting("pending").gte(Selecting("x")) && !Selecting("active") && tmp["Sol"].Custom["112"].canClick) {
 
        if (!Selecting("active"))  player.Sol[player.Sol.selected].active = true
            // reset down below
        layer2Reset()
        player.E.SolarCharge = player.E.SolarCharge.root(10)
        player.E.Solinity =  player.E.Solinity.root(10)
        player.E.Esolar = player.E.Esolar.root(10)
        player.E.Eclipsium = player.E.Eclipsium.root(2)
        player.E.TopLVL = Selecting("pending")
        player.L.Light = new Decimal(1)
        player.L.Dark = new Decimal(1)
        player.L.LunarPower = new Decimal(1)
        player.L.LightCheck = player.L.LightCheck.root(2).round()
        player.L.DarkCheck = player.L.DarkCheck.root(2).round()
        setBuyableAmount("E",12, new Decimal(0))              

  }

  },
  canClick() { 
    
    if (Selecting("active")) return true
                  else return Selecting("pending").gte(1)
  },
  style() {return {
    "width": "150px",
    "height": "40px",
    }},  
  unlocked() {
   if (player.Sol.sub == "WoC") return Selecting("pending").gte(1) || Selecting("active") }
},

113: {
  display() {
    let short = ""
    if (player.Sol.selected == "TMSun") short = `TMS`
    else if (player.Sol.selected == "TRMoon") short = `TRM`
    else if (player.Sol.selected == "TBSun") short = `TBE`

    return `<h2>Increase ${short == "" ? "[???]" : short + "'s"} Difficulty by 1</h2>`
  },
  onClick() {  
    let currentActive = player.Sol.selected
    if ( Selecting("pending").lt(5) && tmp["Sol"].Custom[113].canClick ) player.Sol[currentActive].pending = player.Sol[currentActive].pending.plus(1)

     },
  canClick() {
    let TBCore = player.Sol.TBCore.x

    let noFurther = false
      
      if (TBCore.eq(2) && ( Selecting("pending").plus(Selecting("x")).eq(5) )  )  noFurther = true
      else if (TBCore.eq(1) && ( Selecting("pending").plus(Selecting("x")).eq(3)) ) noFurther = true
      else if (TBCore.eq(0) && ( Selecting("pending").plus(Selecting("x")).eq(2)  ) ) noFurther = true
      

    return !noFurther
  
  },
  style() {return {
    "width": "130px",
    "height": "40px",
    }},  
  unlocked() {return player.Sol.selected != "" && player.Sol.sub == "WoC" && player.Sol[player.Sol.selected].active == false}
},

201: {
  display() {return `<h2>Go back</h2>`},
  onClick() { 
    player.Sol[player.Sol.selected].pending = new Decimal(0)
    player.Sol.selected = ""
  },
  canClick() {return true},
  style() {return {
    "width": "125px",
    "height": "40px",
    }},  
  unlocked() {return player.Sol.selected != "" && player.Sol.sub == "WoC" && player.Sol[player.Sol.selected].active == false}
},

//player.Sol.selected = ""

  },
  
  
  





  Reset: {
    11: {
      display() {
          
          let nBAR = ``

         let CRNG = new Decimal(player.Sol.CRNG)

          let CurrentCPBoost = player["Sol"].Aperativity.clampMin(1).log(10)
          let ifResetNow = tmp["Sol"].Reset[11].gain
          let newCPBoost = player["Sol"].Aperativity.plus(ifResetNow.clampMin(1)).log(10)

          let SecondReset = CRNG.gte(25) ?  `Note: This will reset CRNG` : ``

          

          if (ifResetNow.gte(1) && CurrentCPBoost.gte(1)) nBAR = `CP Base will be increased ${format(CurrentCPBoost)} -> ${format(newCPBoost)}`


          if (player.L.LunarPower.gte(100) || player.L.LunarEssence.gt(0)) return `
            Aperating will reset everything Lunar Restabalize does as well as Lightness and Darkness. Light/Dark check will be set back down to 1 for Aperativity<br> 
            <br> Aperating Requirements: LC and DC #6 or more. and at least 
            <br> You will earn ${format(tmp["Sol"].Reset[11].gain)} Aperativity before reset <br>
            ${nBAR}
            <br>
            ${SecondReset}
            <br>      
          `
          /* 
          formula:
          A = log10(Light x dark) 
          (essentially log10(Light) + log10(Dark))

          (LK# * DK#) * A^0.5

          */

        },     
      onClick() {
        
        player.Sol.Aperativity = player.Sol.Aperativity.plus(Reset("Sol",11).gain)
        
        EclipsiumReset()
        player.L.LightCheck = new Decimal(1)
        player.L.DarkCheck = new Decimal(1)
        player.L.Light = new Decimal(1)
        player.L.Dark = new Decimal(1)
        player.L.LunarPower = new Decimal(0)                                              
        player.E.TopLVL = new Decimal(0)           
        
        CRNG = new Decimal()
        if (player.Sol.CRNG.gte(25)) player.Sol.CRNG = new Decimal(1)
        setClickableState("L", 41, false)
        setClickableState("L", 42, false)

      },
      canClick() {if (player.L.LightCheck.gte(6) && player.L.DarkCheck.gte(6)) return true},
      
      gain: () => { 
        let base = player.L.LightCheck.mul(player.L.DarkCheck).log(3).div(player.Sol.Aperativity.clampMin(1).log(100).clampMin(1)) ; 
        let secondaryBoost = player.L.Light.mul(player.L.Dark).log(10).pow(0.5); 
        if (TSolStones(2).unlocked) secondaryBoost = secondaryBoost.mul(TSolStones(2).effect)
        
        return base.mul(secondaryBoost)
      
      },
      button: () => { return `Aperate!` },
      unlocked() {
         return player.Sol.tab == "Aparal" //this is the base unlock for Eclipse Tier 6
      },
  },          
 },

 Viewer: {
  11: {
    display() {
      
      let Aperate = ``
      
      let selfDiv = (player.Sol.Aperativity.clampMin(1).log(100).gt(1)) ? `<h3> However, The decaying sun is reducing Aperativity by </h3> </h2 tyle="color:rgb(72, 30, 30)"> ${format(player.Sol.Aperativity.clampMin(1).log(100))} </h2>` : ``
      if (player.Sol.Aperativity.gt(0) || true) Aperate = `
      <h2> Aperativity Points: ${format(player.Sol.Aperativity)}<br></h2> 
      <h3> Aperativity increases CP compounding base by +${format(player.Sol.CPBoost)} </h3> <br>
      

      `

      return `      
      ${Aperate}

      
      `

    },
    

    unlocked() {
     return (player.Sol.tab == "Aparal" && player.Sol.Aperativity.gte(1))
    }


  },

  // BRNG Milestones
  12: {
    
    display(getData) {
  
      let BRNG = player.Sol.BRNG
      const SolStones = {
        1: {
          unlocked: BRNG.gte(25),
          text: `>25 BRNG`,
          effect: BRNG.log(3).pow(2.5),
          reward: `Light/Dark generation`
        },
        //^(log10(BRNG)/100) of Lightness boosts itself []
        2: {
          unlocked: BRNG.gte(100),
          text: `>100 BRNG`,
          effect: BRNG.log(3).pow(4),
          reward: `Solarity gain cap`
        },
        3: {
          unlocked: BRNG.gte(250),
          text: `>250 BRNG`,
          effect: BRNG.log(7).pow_base(3).pow(1.5),
          reward: `Solar light cap`
        }, //^(log10(BRNG)/100) of Lightness boosts itself
        4: {
          unlocked: BRNG.gte(1000),
          text: `>1000 BRNG`,
          effect: BRNG.log(10).pow_base(2),
          reward: `Solinity, Esolar, and Chimera`
        },
        5: {
          unlocked: BRNG.gte(4500),
          text: `>4500 BRNG`,
          effect: BRNG.log(15).pow_base(4),
          reward: `Modifier Score`
        },
      } 
       

        let result = ``
              for (id in SolStones) {
                if (SolStones[id].unlocked) {
                result += `
                    <span style="border: 2px solid gray; display: inline-block;"> 
                      ${SolStones[id].text /*? Milestones[id].text : warn("missing text at" + id) */ }
                      <br>
                      Boost ${SolStones[id].reward ? SolStones[id].reward : ""} by ${format(SolStones[id].effect) }
                    </span>
                  <br><br>
                  `
                  
                } 
              }

              let nextUnlock = ``
                if (SolStones[5].unlocked) nextUnlock = ``
                else if (SolStones[4].unlocked) nextUnlock = `Next at 4500 BRNG`
                else if (SolStones[3].unlocked) nextUnlock = `Next at 1000 BRNG`
                else if (SolStones[2].unlocked) nextUnlock = `Next at 250 BRNG`
                else if (SolStones[1].unlocked) nextUnlock = `Next at 100 BRNG`
                
              
                  

      return getData ? SolStones : result != "" ? result : result = `<h3> Unlock at 25 BRNG </h3>`;
 
      
   
    },
    
    style() {
      return {
          "border": "2px solid gray",
					"display": "inline-block",
					"font-size": "12px",
					"background-color":"#202021",	
					"padding": "15px",
					"width": "164px",
      }
    },

    unlocked() {
     return (player.Sol.tab == "RNG")
    }
  },

  13: {
    
    display() {
      
     // let CRNG = new Decimal(1 / RawRNG)
      
      let spentAP = player.Sol.Aperativity.div(10)
      let boosted = Roll.Amount > 0 ? spentAP.root(3) : new Decimal(1)

      let isRolling = isNaN(player.Sol.CRNG)

      let QuantifyBonus = (player.Sol.MNG.Quantify.plus(1).pow_base(1.1).pow(2))
      
      //
      
      let basicDisplays = `
       <span> 
        
            <h3>CRNG: ${ isRolling ? 'Rolling...' : format(player.Sol.CRNG) }</h3><br>
            Raw: ${RawRNG} <br>
            ${!Roll.active && Roll.Amount > 1 ? "Before Bonus: " + format(Roll.trueVal) + `<br><br>`: ""}
            <br>
            <h3>BRNG: ${format(player.Sol.BRNG)}</h3>
           <br>
           <h4> ${Roll.active && boosted.gt(1)? "CRNG boosted by " + format(boosted) + " (based on spent Aperativity) " : ""} </h4>
           
          <br> <h4> ${player.Sol.TRNG.gt(1) ? "TRNG: " + format(player.Sol.TRNG) : ""} </h4>
          ${!Roll.active && Roll.Amount > 0 && player.Sol.MNG.Quantify.gte(1) ? "(+" + format(player.Sol.CRNG.mul(QuantifyBonus)) + ")" : ""}
          <br>


       </span>
       ` 


       let canRoll = (Roll.cooldown <= 0 ) ? `Roll again!` : `Cooldown: ${Math.ceil(Roll.cooldown)}`
       if (player.Sol.Aperativity.lte(15)) canRoll = `Cannot Roll: Aperativity is too low`


       let roller = `
          <span>
            <button style="width:224px" onclick="Roll.cooldown <= 0 && player.Sol.Aperativity.gt(15) ? tmp['Sol'].Viewer[13].rollAP() : 0"; > ${(canRoll)} </button>

          </span>
       `
        
      return basicDisplays + roller
 
    },
    
    async rollAP() { 
  
        // set values
        let spentAP = player.Sol.Aperativity.div(10)
        let boosted = Roll.Amount > 0 ? spentAP.root(3) : new Decimal(1)


        //turn on Roll
        Roll.active = true
        roll()
        
        //wait for animation to be over
        await delay(100 + ((100 + player.Sol.MNG.Rans) * Roll.baseCoolDown ) * (simulated.length) )
        //boost TRNG

        let QuantifyBonus = player.Sol.MNG.Quantify.gte(1) ? (player.Sol.MNG.Quantify.plus(1).pow_base(1.1).pow(2)) : 1


       
          player.Sol.TRNG = player.Sol.TRNG.plus(player.Sol.CRNG.mul(QuantifyBonus))


        //set CRNG
        player.Sol.CRNG = new Decimal(1 / RawRNG)
        Roll.trueVal = player.Sol.CRNG
        if (player.Sol.Aperativity.gte(15)) player.Sol.CRNG = player.Sol.CRNG.mul(boosted)
        if (player.Sol.MNG.Elevate.gte(1))  player.Sol.CRNG = player.Sol.CRNG.mul(player.Sol.MNG.Elevate.mul(2).pow_base(1.2))

        //detect for BRNG
        if (player.Sol.CRNG.gt(player.Sol.BRNG)) player.Sol.BRNG = player.Sol.CRNG

        //spend AP
        player.Sol.Aperativity = player.Sol.Aperativity.sub(spentAP) 
        Roll.Amount += 1

        //finish rolling
        Roll.active = false

       
    },

    style() {
      return {
          "border": "2px solid gray",
					"display": "inline-block",
					"font-size": "12px",
					"background-color":"#202021",	
					"padding": "15px",
					"width": "224px",
      }
    },

    unlocked() {
     return (player.Sol.tab == "RNG")
    }
  },

  14: {
    
    display(getData) {

      let CRNG = new Decimal(player.Sol.CRNG)
      let TRNG = player.Sol.TRNG
      const TSolStones = {
        1: {
          unlocked: TRNG.gte(10) || player.Sol.MNG.Total.gte(1),
          text: `TRNG-1`,
          effect: TRNG.pow(2),
          reward: `Boost Solarity gain by ` + format(TRNG.pow(2))
        },
        2: {
          unlocked: TRNG.gte(30) || player.Sol.MNG.Total.gte(1),
          text: `TRNG-2`,
          effect: CRNG.log(7).pow(1.25).plus(1),
          reward: `Boost Aperature Points gain by ` + format(CRNG.log(7).pow(1.5).plus(1)) + ` (Based on CRNG)`
        },
        3: {
          unlocked: TRNG.gte(100) || player.Sol.MNG.Total.gte(1),
          text: `TRNG-3`,
          reward: `Unlock MNG`
        },
        4: {
          unlocked: TRNG.gte(500) && player.Sol.MNG.Total.gte(1),
          text: `TRNG-4`,
          reward: `Unlock Aperativity upgrades`
        },
        5: {
          unlocked: TRNG.gte(1000) && player.Sol.MNG.Total.gte(1),
          text: `TRNG-5`,
          reward: `Unlock the ability to store CRNG for SRNG`
        },
        6: {
          unlocked: TRNG.gte(5000),
          text: `TRNG-5`,
          reward: ``
        },
      } 
       

        let result = ``
              for (id in TSolStones) {
                if (TSolStones[id].unlocked) {
                result += `
                    <span style="border: 2px solid gray; display: inline-block;"> 
                     <h3> ${TSolStones[id].text } </h3>
                      <br>
                      ${TSolStones[id].reward ? TSolStones[id].reward : ""}  
                    </span>
                  <br><br>
                  `
                } 
              }
          let nextUnlock = ``
                if (TSolStones[5].unlocked) nextUnlock = `Next at 5000 TRNG`
                else if (TSolStones[4].unlocked) nextUnlock = `Next at 1000 TRNG`
                else if (TSolStones[3].unlocked) nextUnlock = `Next at 500 TRNG`
                else if (TSolStones[2].unlocked) nextUnlock = `Next at 100 TRNG`
                else if (TSolStones[1].unlocked) nextUnlock = `Next at 30 TRNG`
                 

         // if (getData == TSolStones[3].effect && TSolStones[3].effect == undefined) alert("hey! This id doesn't have an effect!");    
      return getData ? TSolStones : result != "" ? result + nextUnlock : result = `<h3> Unlock at 10 TRNG </h3>`;
 
      
   
    },
    
    style() {
      return {
          "border": "2px solid gray",
					"display": "inline-block",
					"font-size": "12px",
					"background-color":"#202021",	
					"padding": "15px",
					"width": "164px",
      }
    },

    unlocked() {
     return (player.Sol.tab == "RNG")
    }
  },

//<button> Roll BRNG </button>
 


21: {
  display() {
    let E1 = ``
    let E2 = ``
    let E3 = ``
    let SE1 = ``
    let SE2 = ``
    // 
    if (player.Sol.SolarHeat.gt(1)) E1 = `${format(player.Sol.SolarHeat.pow(3.75))} to solarity gain cap <br>`
    if (player.Sol.SolarHeat.gte(50)) E2 = `${format((player.Sol.SolarHeat.sub(50)).pow_base(1.02))} to Heirarchy's effect <br>`
    if (player.Sol.SolarHeat.gt(1)) E3 = ` <h4 style="color:rgba(159, 22, 22, 0.99);">/${format((player.Sol.SolarHeat.sub(1).root(2.5)).pow_base(1.02))}</h4> to modifier score  ` 

    if (player.Sol.SolarHeat.gt(1)) SE1 = `${format(player.Sol.SolarFragments.pow(2.4))} to SR Gain <br>`
    if (player.Sol.SolarHeat.gt(1)) SE2 = `${format(player.Sol.SolarFragments.log(10).div(100))} to SR Exponent <br>`
    // player.Sol.SolarFragments.pow(2.4) 

    // player.Sol.SolarFragments.log(10).div(100) //from Solar Fragments, which increase SR exponent


    

    let Bonuses = `
     <span style="border: 2px solid gray; display: inline-block; padding: 6px;">
          <h3> Solar Heat Bonuses: </h3> <br>    
            ${E1}
            ${E2}
            ${E3}
      </span>

      <span style="border: 2px solid gray; display: inline-block; padding: 6px;">
          <h3> Solar Fragments Bonuses: </h3> <br> 
            ${SE1}
            ${SE2}
      </span>
     
    `
   
    let tutorial = ``

    if (player.Sol.SolarHeat.gt(1) && player.Sol.SolarFragments.lte(1)) tutorial = `*burp*<br>`

    else if (player.Sol.SolarHeat.eq(1) && player.Sol.SolarFragments.eq(1)) tutorial = `<p> click on an object to begin Generating it! </p> <br>(Note that starting generation is similar to doing a convertary reset)<br>`

    else tutorial = ``


    return `
      
    ${tutorial}
    <span style="border: 2px solid gray; display: inline-block; padding: 6px;">      
      <h3>
        ${format(player.Sol.SolarHeat)} Solar Heat. <br>
        ${format(player.Sol.SolarFragments)} Solar fragments <br>
        </h3>
    </span>

    ${Bonuses}


    `
  },

  unlocked() {
   return (player.Sol.tab == "Core" && player.Sol.sub == "Heliosphere" && player.Sol.Heliosphere)
  },
 style() {
      return {
          "border": "2px solid gray",
					"display": "inline-block",
					"font-size": "12px",
					"background-color":"#202021",	
					"padding": "15px",
					"width": "600px",
      }
    },

 


},


//not yet
31: {
  display() {
    let TMSun = player.Sol.TMSun.x
    let TRMoon = player.Sol.TRMoon.x
    let TBSun = player.Sol.TBSun.x
    let TBCore = player.Sol.TBCore.x

    let TMSunP = player.Sol.TMSun.pending
    let TRMoonP = player.Sol.TRMoon.pending
    let TBSunP = player.Sol.TBSun.pending
    let TBCoreP = player.Sol.TBCore.pending

    let choosingScale = Selecting("pending") == undefined ? new Decimal(0) : Selecting("pending").plus(Selecting("x"))
    let BC_Influence = ``
    //if (player.Sol.selected != "")  choosingScale = player.Sol[player.Sol.selected].pending  
 
    const TMSDebuff = [
      `- Solar light cap and modifier score is capped to ${format(new Decimal(100000).div(choosingScale.sub(1).pow_base(10)))} <br>`
      ,
      `- Solarity gain cap is rooted to ${format(new Decimal(5).pow(choosingScale.div(10)))} <br>`
      ,
      `- Multiply’s effect is capped to Plasmates effect <br>`
    ]
    const TRMDebuff = [
      `- CP cost scaling requirement is increased by ${format(choosingScale.pow_base(1.1).mul(100).sub(100))}% <br>`
      ,
      `- Phaser’s cost scaling is Overhauled to ${choosingScale}^x <br>`
      ,
      `- Completely Overhaul Plasmates and Multiply's cost scalings 4^x But Meta nerf is disabled <br>`
    ]
    const TBSDebuff = [
      `- Lunar Inst. debuff is significantly stronger (^${format(choosingScale.mul(2).plus(1))}) <br>`
      ,
      `- Lunar Inst. debuff also affects SR gain and Solar Shards gain (^${format(choosingScale.sub(1).div(15))}) <br>`
      ,
      `- Lunar Inst. debuff also affects Plasmates and Multiply (^0.44)<br>`
    ]
    const TBCDebuff = [
          `Convertary resets CP layer and Centralizing resets SL Layer. <br>`
          ,
          `Buying any type of upgrade resets all currencies of its own layer <br>`
          ,
          `All 3 check upgrades are active at once. in addition, ALL pre-check measures are active<br>`
    ]
    //NON-QOL BONUS



    const TMSBuff = [
       `${decimalOne.plus(TMSun.mul(0.15))} to Solar light cap and Shards (Gen. AND Mult.)<br>`,
          , //hasMilestone("E",5)
          `Eclipsium effect base is increased +${decimalOne.plus(TMSun.mul(0.03))}. It's cap is moved to ${new Decimal(1e10).mul(TMSun.pow_base(1e10))} <br>`
          ,
          `Plasmate is raised ^1.1 <b>(+0.01 per minute on latest reset)<br>`      

    ]
    const TRMBuff = [
          `-${TRMoon.mul(0.02)} to CP cost scaling requirement <br>`
          ,
          `-${TRMoon.sub(2).mul(0.02)} to Phasers cost scaling<br>`
          , 
          `Multiply's Meta nerf starts +50 Later <b>(+1 per minute on latest reset)<br>`

    ]
    const TBSBuff = [
       `^${new Decimal(0.9).pow(TBSun)} to Lunar Inst. debuff <br>`
          ,
       `+${TBSun.sub(2).mul(0.1)} to Solar light to Solar shard conversion rate exponent <br>`
          ,
       `Multiply's base is increased +0.2 <b>(+0.01 per minute on latest reset)</b>`
    ]

    const TBCoreBuff = [
      `Solar Shard gain is ^1((0.25*A)*1.5^A)`,
      `All Effector Tiers effects are ^3`,
      `<b> You're ready... </b> - Solar Light to Solar shards conversion is increased from 0.4 to 0.6`
    ]

     const ProjectedTMSBuff = [
         `${decimalOne.plus(TMSunP.plus(TMSun).mul(0.15))} to Solar light cap and Shards (Gen. AND Mult.)<br>`,
          ,
          `Eclipsium effect base is increased +${decimalOne.plus(TMSun.plus(TMSun).mul(0.03))}. It's cap is moved to ${new Decimal(1e10).mul(TMSunP.plus(TMSun).pow_base(1e10))} <br>`
          ,
          `Plasmate is raised to ^2 <br>`      

    ]
    const ProjectedTRMBuff = [
       ` -${TRMoonP.mul(0.02)} to CP cost scaling requirement <br>`
          ,
          `-${TRMoonP.sub(2).mul(0.02)} to Phasers cost scaling <br>`
          ,
          `Lunar Inst. debuff also affects Plasmates and Multiply (^0.44)<br>`

    ]
    const ProjectedTBSunBuff = [
       `^${new Decimal(0.9).pow(TBSunP)} to Lunar Inst. debuff <br>`
          ,
       `+${TBSunP.sub(2).mul(0.1)} to Solar light to Solar shard conversion rate exponent <br>`
          ,
       `Lunar Inst. debuff also affects Plasmates and Multiply (^0.44) <br>`
    ]

    const ProjectedTBCoreBuff = [
      
    ]

    if (player.Sol.TBCore.pending.eq(2)) BC_Influence = `
    <h3> Broken core's influence: </h3><br>
    TMS2 and TBS3 is active <br><br>
      <span style='color:rgba(170, 186, 2, 0.99)';> 
        (caps Solar light and Modifier score to 10,000) <br> 
        (Lunar inst. debuff is raised to ^6, and affects Solar Ray's and Solar Shards gain) <br> 
        </span>
    `
    else if (player.Sol.TBCore.pending.eq(1)) BC_Influence = `
      <h3> Broken core's influence: </h3><br>
      TMS1 and TRM2 is active <br><br>
      <span style='color:rgba(0, 133, 2, 0.99)';>  
        (caps Solar light and Modifier score to 100,000) <br> 
        (increases CP scale by 21%) </span>
      `
  //player.Sol.selected == "TMSun"
    let type = ``
     {
      if (player.Sol.selected == "TMSun") {
        type = `
            <span> 
              <h2> The Melted Sun ( ${TMSun} / 5 ) </h2>
            </span>
            <br>
              
             Pre-check measures: Leverage and Gravitation is disabled. Convertary is also disabled <br> 
             <h3>
             <span style='color:rgba(80, 44, 225, 0.99)';>
            ${ choosingScale.gte(1) ? TMSDebuff[0] : ""   }
            ${ choosingScale.gte(3) ? TMSDebuff[1] : ""   }
            ${ choosingScale.gte(5) ? TMSDebuff[2] : ""   }
            </span>
             </h3>
            `
      } else if (player.Sol.selected == "TRMoon") {
        type = `
            <span> 
              <h2> The Raging Moon ( ${TRMoon} / 5 ) </h2>
              
            <br>
             Pre-Check measures: Extra CP gained from TRNG-5 are disabled.<br>
              <h3>
                <span style='color:rgba(114, 15, 53, 0.99)';>
                  ${ choosingScale.gte(1) ? TRMDebuff[0] : ""   }
                  ${ choosingScale.gte(3) ? TRMDebuff[1] : ""   }
                  ${ choosingScale.gte(5) ? TRMDebuff[2] : ""   }
              </h3>  
            </span>
            `
      } else if (player.Sol.selected == "TBSun") {
        type = `
            <span> 
              <h2> The Bleeding Sun ( ${TBSun} / 5 ) </h2>
            </span>
            <br>
            Pre-check measures: The Solar ray bonuses are disabled <br>
              <h3>
              <span style='color:rgba(145, 76, 41, 0.99)';>
            ${ choosingScale.gte(1) ? TBSDebuff[0] : ""   }
            ${ choosingScale.gte(3) ? TBSDebuff[1] : ""   }
            ${ choosingScale.gte(5) ? TBSDebuff[2] : ""   }
               </span>
              </h3> 
            `
      } else if (player.Sol.selected == "TBCore") { // player.Sol.TMSun.x.sub(2).mul(0.02)
        type = `
            <span> 
              <h2> The Broken Core ( ${TBCore} / 5 ) </h2>
            </span>
             Pre-check measures (I): All other check upgrades and effects are disabled
             ${TBCore.gte(1) ? "Pre-check measures (II): The first 3 Bonus effects are disabled" : ""} 
             ${TBCore.gte(2) ? "Pre-check measures (III): The last 3 Bonus effects are disabled" : ""} 
              <h3>
              <span style='color:rgba(255, 0, 0, 0.99)';>
                ${ choosingScale.gte(1) ? TBCDebuff[0] : ""   }
                ${ choosingScale.gte(2) ? TBCDebuff[1] : ""   }
                ${ choosingScale.gte(3) ? TBCDebuff[2] : ""   }
                </span>
              </h3>

            ${BC_Influence}

         </span>
            `
      } //player.Sol.TRMoon.x
  } 

//TRMoon.gte(1)
  let unknown=`???<br>`


const buffColor = 'rgba(100, 222, 0, 0.99)';
const projectedBuffColor = 'rgba(255, 226, 60, 0.99)';



  let totalBonus = `
  
      <span style="border: 2px solid gray; display: inline-block;"> 
          All possible bonus effects <br><br>
          
      ${ TMSun.gte(1) && TMSun.neq(TMSunP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TMSBuff[0] + " </span>" : unknown  } ${ TMSunP.gte(1) && TMSun.gte(0) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTMSBuff[0] + " </span>" : ""   }
      ${ TMSun.gte(3) && TMSun.neq(TMSunP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TMSBuff[1] + " </span>" : unknown   } ${ TMSunP.gte(3) && TMSun.gte(2) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTMSBuff[1] + " </span>" : ""   }
      ${ TMSun.gte(5) && TMSun.neq(TMSunP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TMSBuff[2] + " </span>" : unknown  } ${ TMSunP.gte(5) && TMSun.gte(4) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTMSBuff[2] + " </span>" : ""   }
        
      ${ TRMoon.gte(1) && TRMoon.neq(TRMoonP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TRMBuff[0] + "</span>": unknown  } ${ TRMoonP.gte(1) && TRMoon.gte(0) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTRMBuff[0] + " </span>" : ""   }
      ${ TRMoon.gte(3) && TRMoon.neq(TRMoonP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TRMBuff[1] + "</span>": unknown  } ${ TRMoonP.gte(3) && TRMoon.gte(2) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTRMBuff[1] + " </span>" : ""   }
      ${ TRMoon.gte(5) && TRMoon.neq(TRMoonP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TRMBuff[2] + "</span>": unknown   } ${ TRMoonP.gte(5) && TRMoon.gte(4) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTRMBuff[2] + " </span>" : ""   }
      
      ${ TBSun.gte(1) && TBSun.neq(TBSunP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBSBuff[0] + "</span>" : unknown   } ${ TBSunP.gte(1) && TBSun.gte(0) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTBSunBuff[0] + " </span>" : ""   }
      ${ TBSun.gte(3) && TBSun.neq(TBSunP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBSBuff[1] + "</span>" : unknown   } ${ TBSunP.gte(3) && TBSun.gte(2) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTBSunBuff[1] + " </span>" : ""   }
      ${ TBSun.gte(5) && TBSun.neq(TBSunP) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBSBuff[2] + "</span>" : unknown   } ${ TBSunP.gte(5) && TBSun.gte(4) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTBSunBuff[2] + " </span>" : ""   }
    
      ${ TBCore.eq(1) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBCoreBuff[0] + "</span>" : unknown   } ${ TBCoreP.gte(1) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTBCoreBuff[0] + " </span>" : ""   }
      ${ TBCore.eq(2) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBCoreBuff[1] + "</span>" : unknown   } ${ TBCoreP.gte(2) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTBCoreBuff[1] + " </span>" : ""   }
      ${ TBCore.eq(3) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBCoreBuff[2] + "</span>" : unknown   } ${ TBCoreP.gte(3) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + ProjectedTBCoreBuff[2] + " </span>" : ""   }


      </span>
      
      <span style="border: 2px solid gray; display: inline-block;"> 
          All possible QoL effects <br><br>
         
         ${ TMSun.gte(1) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TMSQoL[0] + " </span>" : unknown  } ${ TMSunP.gte(1) && TMSun.neq(TMSunP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TMSQoL[0] + " </span>" : ""   }
            ${ TMSun.gte(3) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TMSQoL[1] + " </span>" : unknown  } ${ TMSunP.gte(3) && TMSun.neq(TMSunP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TMSQoL[1] + " </span>" : ""   }
            ${ TMSun.gte(5) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TMSQoL[2] + " </span>" : unknown   } ${ TMSunP.gte(5) && TMSun.neq(TMSunP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TMSQoL[2] + " </span>" : ""   } 
           
        ${ TRMoon.gte(1) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TRMQoL[0] + "</span>": unknown  } ${ TRMoonP.gte(1) && TRMoon.neq(TRMoonP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TRMQoL[0] + " </span>" : ""   }
          ${ TRMoon.gte(3) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TRMQoL[1] + "</span>": unknown   } ${ TRMoonP.gte(3) && TRMoon.neq(TRMoonP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TRMQoL[1] + " </span>" : ""   }
          ${ TRMoon.gte(5) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TRMQoL[2] + "</span>": unknown   } ${ TRMoonP.gte(5) && TRMoon.neq(TRMoonP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TRMQoL[2] + " </span>" : ""   }
        
        ${ TBSun.gte(1) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBSQoL[0] + "</span>" : unknown   } ${ TBSunP.gte(1) && TBSun.neq(TBSunP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TBSQoL[0] + " </span>" : ""   }
            ${ TBSun.gte(3) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBSQoL[1] + "</span>" : unknown   } ${ TBSunP.gte(3) && TBSun.neq(TBSunP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TBSQoL[1] + " </span>" : ""   }
            ${ TBSun.gte(5) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBSQoL[2] + "</span>" : unknown  } ${ TBSunP.gte(5) && TBSun.neq(TBSunP) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TBSQoL[2] + " </span>" : ""   }
        
        ${ TBCore.eq(1) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBCQoL[0] + "</span>" : unknown   } ${ TBCoreP.gte(1) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TBCQoL[0] + " </span>" : ""   }
            ${ TBCore.eq(2) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBCQoL[1] + "</span>" : unknown   } ${ TBCoreP.gte(2) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TBCQoL[1] + " </span>" : ""   }
            ${ TBCore.eq(3) ? "<span style='color:rgba(100, 222, 0, 0.99)';>" + TBCQoL[2] + "</span>" : unknown   } ${ TBCoreP.gte(3) ? "<span style='color:rgba(255, 226, 60, 0.99)';>" + TBCQoL[2] + " </span>" : ""   }
     
      </span>
    `
  //TMSQoL , TRMQoL , TBSQoL


    let stats = `
    <h3>${TMSun.gte(1) ? "Melted Sun " + TMSun : "Melted Sun Ø"}, ${TRMoon.gte(1) ? "Raging Moon " + TRMoon : "Raging Moon Ø"}, ${TBSun.gte(1) ? "Bleeding Eclipse  " + TRMoon : "Bleeding Eclipse Ø"} </h3>
    
    `

    return `
    Studies made: ${stats}

    <br><br>
    ${type}
      <br>
    ${totalBonus}

    `
  },

  unlocked() {
   return (player.Sol.sub == "WoC")
  },
 style() {
      return {
          "border": "2px solid gray",
					"display": "inline-block",
					"font-size": "12px",
					"background-color":"#202021",	
					"padding": "15px",
					"width": "600px",
      }
    },


},



 },




 upgrades: {
  11: {
    fullDisplay() {
        let reward = ""
        if (hasUpgrade("Sol",this.id)) reward = `<span style='text-decoration: underline;'>Reward:</span><br> add +${format(player.Sol.CPBoost.root(4).sub(1),3)} to annular's max exponent`
      
        return `
          <h3> Extenditality </h3><br><br>
          Queued Upgrade 5: <br>
          Get 2.77e91 Solarity Without Annular While Converting for Solar Light while inside light check <br><br>
          
          ${reward}
        `
    },
    unlocked() {
      if (player.Sol.tab == 'Aparal') return true
      },
    style() {
      
      return Tier2QueuedUpgs
    },
    effect() {
      return player.Sol.CPBoost.root(4).sub(1)

    },
    canAfford() {
     let firstGoal = player.points.gte(2.77e91)
     let noAnnular = hasUpgrade("GL",21) ? false : true
     let mustBeIn = getClickableState("L",41) && getClickableState("GL", 11)
     
     //let restrictions = (!hasUpgrade())

	  return mustBeIn && noAnnular && firstGoal
    },
    pay() {
      EclipsiumReset(true)
      player.L.Light = new Decimal(1)
      player.L.Dark = new Decimal(1)
      player.L.LunarPower = player.L.LunarPower.root(5)                      
     }

},

  12: {
  fullDisplay() {
    let capIncrease = ``
    let effect = player.S.points.pow(0.09)
    if (getClickableState("L",42) && hasUpgrade("Sol",this.id)) capIncrease = `and it's cap`

    let reward = ``
    let Dreward = ``


    if (getClickableState("L",42) && hasUpgrade("Sol",this.id)) Dreward = `<p>+ : ${format(player["S"].bestPointsInDark.pow(1/0.09))} -> ${format(player["S"].bestPointsInDark)} to SR cap </p>`
    if (hasUpgrade("Sol",this.id)) reward = `<span style='text-decoration: underline;'>Reward:</span><br> ^0.09 of Solar Rays boost themselves ${capIncrease} <br>
   SD-104's effect is ${format(effect)}<br>
    `
      return `
        <h3> SD-104 </h3> <br><br>
       Queued Upgrade 6: <br>
       Get 5.1e14 Solar rays (Multipliers) without Gravitation, Solar Shard Upgrades, While inside Dark check <br>
        
       ${reward}
      ${Dreward}
      `
  },
  unlocked() {
    if (player.Sol.tab == 'Aparal') return true
    },
  style() {
    
    return Tier2QueuedUpgs
  },
  effect() {
    return player.S.points.pow(0.09).clampMin(1)

  },
  canAfford() {
    let firstGoal = tmp["S"].getResetGain.gte(4.48e13) //when the multipliers reach 1e10 Solar Rays

    // 1.01e14 <- when Solar Rays mult is 1.5e10

    let Anti_has = true
    let mustBeIn = getClickableState("L",42) 
    let upgs = [11,12,13,21,31]
    for (id in upgs) hasUpgrade("GL",upgs[id]) ? Anti_has = false : 0;


   //
   //let restrictions = (!hasUpgrade())

  return mustBeIn && (Anti_has && !hasUpgrade("S",13)) && firstGoal 
  },
  pay() {
    EclipsiumReset(true)
    player.L.Light = new Decimal(1)
    player.L.Dark = new Decimal(1)
    player.L.LunarPower = player.L.LunarPower.root(5)                          
   }

},
  13: {
  fullDisplay() {
    
   // let effect = player.S.points.pow(0.09)

    let reward = ""
    if (hasUpgrade("Sol",this.id)) reward = `<span style='text-decoration: underline;'>Reward:</span><br> 
    Raise solarity gain cap by ^1.15 while inside light check<br>
    Raise dark essence gain by ^1.05
    
    `
    
    
      return `
        <h3> Miscolosia </h3> <br><br>
       Queued Upgrade 7: <br>
       Heirarchy bonus reaches 7.77e77 without any Darkness tree upgrades while inside light check <br>
        
       ${reward}

      `
  },
  unlocked() {
    if (player.Sol.tab == 'Aparal') return true
    },
  style() {
    
    return Tier2QueuedUpgs
  },

  canAfford() {
    let firstGoal = GetHeirarchyBonus().gte(7.77e77)

    let noCenterUpgrades = true
    let mustBeIn = getClickableState("L",41) 
    let upgs = [11,12,13,21,22,23]
    for (id in upgs) hasUpgrade("C", upgs[id]) ? noCenterUpgrades = false : 0;


   //
   //let restrictions = (!hasUpgrade())

  return mustBeIn && noCenterUpgrades && firstGoal
  },
  pay() {
    EclipsiumReset()
    player.L.Light = new Decimal(1)
    player.L.Dark = new Decimal(1)
    player.L.LunarPower = player.L.LunarPower.root(5)                      
   }

}, 
  14: {
  fullDisplay() {

    let reward = ""
    if (hasUpgrade("Sol",this.id)) reward = `<span style='text-decoration: underline;'>Reward:<br>
    </span>
     Unlock The Randomizor. also <br>
     = This will be the last of queued and quest upgrades in Enlightenment, I Hope you're ready for what's next :)
    <br>

    `
      
    
      return `
        <h3> Solarify </h3> <br><br>
       Queued Upgrade 8: <br>
       4.44e15 Lightness and Darkness <br>
       Have over 7.15e50 Dark Essence in Dark check under 1 CP without any Darkness Tree upgrades
       
  <br>
        
       ${reward}

      `
  },
  unlocked() {
    if (player.Sol.tab == 'Aparal') return true
    },
  style() { 
    return Tier2QueuedUpgs
  },
  
  canAfford() {
    let firstHandReq = player.L.Light.gte(4.44e15) && player.L.Dark.gte(4.44e15)
    let secondaryReq = player.points.gte(7.15e50)
    let under1CP = player.C.CenterPoints.lt(1) ? true : false
    let mustBeIn = getClickableState("L",42) 

   

   return mustBeIn && under1CP && firstHandReq && secondaryReq
  },
  pay() {
    EclipsiumReset(true)
   player.L.Light = new Decimal(1)
   player.L.Dark = new Decimal(1)
   player.L.LunarPower = player.L.LunarPower.root(5)                        
  }

},
 },

 //Done, Rebalance later
    clickables: { 
    
    11: {   
      display() {
      
      let preBonus = player.Sol.MNG.Rans > 0 ? `
      5 -> ${format(5 / ( (1.06 ** player.Sol.MNG.Rans) ),2)} 
      Or /${format(1.06 ** player.Sol.MNG.Rans)}
      ` : ``
      
       // [1.1 second cooldown minimum]   

      return `
        Ransial #${player.Sol.MNG.Rans} (max 25)
        reduce cooldown duration by 6% per level
        ${preBonus}

        Cost: ${format(getScale(11)[0])} CRNG, ${format(getScale(11)[1])} TRNG

        `
        
      },
      onClick() {
       // Clickable("Sol",11).canClick
       player.Sol.MNG.Rans += 1
    //   player.Sol.MNG.Total = player.Sol.MNG.Total.plus(1)
       player.Sol.CRNG = player.Sol.CRNG.sub(getScale(11)[0])
       player.Sol.TRNG = player.Sol.TRNG.sub(getScale(11)[1])
      },

      scale() {
        //3x compounding
        let base1 = new Decimal(10) // CRNG
        let base2 = new Decimal(25) // TRNG
        let scaleJump = new Decimal(player.Sol.MNG.Rans).pow_base(1.5)
                
        base1 = base1.mul(scaleJump)
        base2 = base2.mul(scaleJump)
        

        return [base1, base2];
      },

  canClick() {
    return player.Sol.CRNG.gte(getScale(11)[0]) && player.Sol.TRNG.gte(getScale(11)[1]) && player.Sol.MNG.Rans < 26
  },
  style() { return MNGStyle
      },   
      
unlocked() {
  if (player.Sol.tab == "RNG" && (TSolStones(3).unlocked || player.Sol.MNG.Total.gte(1))) return true

}
    },
    12: {
      display() {
        return `
          Quantify #${player.Sol.MNG.Quantify}
          Gain more TRNG based on Quantify levels

           ${player.Sol.MNG.Quantify.gt(0) ? "Effect: " + format(player.Sol.MNG.Quantify.plus(1).pow_base(1.1).pow(2)) + " TRNG": ""}

          Cost: ${format(getScale(12)[0])} CRNG, ${format(getScale(12)[1])} TRNG

          `
          
        },
        onClick() {
          player.Sol.MNG.Quantify = player.Sol.MNG.Quantify.plus(1)
         // player.Sol.MNG.Total = player.Sol.MNG.Total.plus(1)
          player.Sol.CRNG = player.Sol.CRNG.sub(getScale(12)[0])
          player.Sol.TRNG = player.Sol.TRNG.sub(getScale(12)[1])
        },

        scale() {
          //3x compounding
          let base1 = new Decimal(10) // CRNG
          let base2 = new Decimal(25) // TRNG
          let scaleJump = new Decimal(player.Sol.MNG.Quantify).pow_base(1.33452)
                  
          base1 = base1.mul(scaleJump)
          base2 = base2.mul(scaleJump)
          
  
          return [base1, base2];
        },

    canClick() {return player.Sol.CRNG.gte(getScale(12)[0]) && player.Sol.TRNG.gte(getScale(12)[1])},
    style() { return MNGStyle
        },   
        
  unlocked() {
    if (player.Sol.tab == "RNG" && (TSolStones(3).unlocked || player.Sol.MNG.Total.gte(1))) return true
  
  }
    },
    21: {
      display() {
      
        return `
          Elevate #${player.Sol.MNG.Elevate}
          Gain more CRNG based on Elevate Levels

           ${player.Sol.MNG.Elevate.gt(0) ? "Effect: " + format(player.Sol.MNG.Elevate.mul(2).pow_base(1.2)) + " CRNG": ""}

          Cost: ${format(getScale(21)[0])} CRNG, ${format(getScale(21)[1])} TRNG

          `
          //player.Sol.MNG.Elevate = new Decimal(10)
        },
        onClick() {
          player.Sol.MNG.Elevate = player.Sol.MNG.Elevate.plus(1)
          // player.Sol.MNG.Total = player.Sol.MNG.Total.plus(1)
           player.Sol.CRNG = player.Sol.CRNG.sub(getScale(21)[0])
           player.Sol.TRNG = player.Sol.TRNG.sub(getScale(21)[1])
        },
        scale() {
          //3x compounding
          let base1 = new Decimal(35) // CRNG
          let base2 = new Decimal(150) // TRNG
          let scaleJump = player.Sol.MNG.Elevate.pow_base(1.25)
                  
          base1 = base1.mul(scaleJump)
          base2 = base2.mul(scaleJump)
          
  
          return [base1, base2];
        },
        canClick() {
          return player.Sol.CRNG.gte(getScale(21)[0]) && player.Sol.TRNG.gte(getScale(21)[1]) 
        },
    style() { return MNGStyle },   
        
  unlocked() {
    if (player.Sol.tab == "RNG" && (TSolStones(3).unlocked || player.Sol.MNG.Total.gte(1))) return true
  }

    },
    22: {
      display() {
        let Next = `<span style="color:rgba(0, 0, 0, 0.75); text-shadow: 0px 0px 0px rgba(255, 255, 255, 0)"> -> ^${ReplicEffect(1)} </span>`
        let Next2 = `<span style="color:rgba(0, 0, 0, 0.4); text-shadow: 0px 0px 0px rgba(255, 255, 255, 0)"> -> ^${ReplicEffect(2)}</span>`
        let Next3 = `<span style="color:rgba(0, 0, 0, 0.15); text-shadow: 0px 0px 0px rgba(255, 255, 255, 0)"> -> ^${ReplicEffect(3)}</span>`
        let nexts = Next + Next2 + Next3
        return `
          Replication #${player.Sol.MNG.Replic}
          Light and Dark Boost themselves at a small rate. 
          ^${ReplicEffect(0)}${nexts}

          Cost: ${format(getScale(22)[0])} CRNG, ${format(getScale(22)[1])} TRNG
          ` 
        },
        onClick() {
          player.Sol.MNG.Replic = player.Sol.MNG.Replic + 1
          // player.Sol.MNG.Total = player.Sol.MNG.Total.plus(1)
           player.Sol.CRNG = player.Sol.CRNG.sub(getScale(22)[0])
           player.Sol.TRNG = player.Sol.TRNG.sub(getScale(22)[1])
        },
      scale() {
          //3x compounding
          let base1 = new Decimal (45) // CRNG
          let base2 = new Decimal (200) // TRNG
          let hyper = new Decimal (player.Sol.MNG.Replic / 100)
          let scaleJump = new Decimal(player.Sol.MNG.Replic).pow_base(hyper.plus(1.1))
                  
          base1 = base1.mul(scaleJump)
          base2 = base2.mul(scaleJump)
          
  
          return [base1, base2];
        },
    canClick() {return player.Sol.CRNG.gte(getScale(22)[0]) && player.Sol.TRNG.gte(getScale(22)[1]) },
    style() { return MNGStyle
        },   
        
  unlocked() {
    if (player.Sol.tab == "RNG" && (TSolStones(3).unlocked || player.Sol.MNG.Total.gte(1))) return true
  
  }

    },

  },
      onClick() {
        player.Sol.genActive=1
      },
      
      unlocked() {
        return (player.Sol.tab == "Core" && player.Sol.sub == "Heliosphere" && player.Sol.Heliosphere)
       },
  canClick() {return true},
  style() {
    return{
      "width": "300px",
      "height": "25px",
      "border-radius": "20px",
      "border": "10px",
      "margin": "10px",
      "text-shadow": "0px 0px 10px #000000",
      }
    
      },   
      
      
 
    32: {
      branches: ["31"],

      
      //getBuyableAmount(this.layer,this.id).div(100)
    display() {

      let exp = format(getBuyableAmount("Sol",11).div(100).plus(0.05),2)
      let gen = player.Sol.genActive=='2' ? ` <br>Generating... (^${exp} of Solar Heat) <br> = ${format(gainOf("Solar Fragments"))} ` : `` 


      return` <h2>
   Start Solar Fragments generation! </h2> <h4> ${gen}
  `
   
    },
    onClick() {
      player.Sol.genActive=2
    },
    
    unlocked() {
      return (player.Sol.tab == "Core" && player.Sol.sub == "Heliosphere" && player.Sol.Heliosphere)
     },
canClick() {return true},
style() {
  return{
    "width": "200px",
    "height": "25px",
    "border-radius": "50px",
    "border": "10px",
    "margin": "15px",
    "text-shadow": "0px 0px 10px #000000",
    }
  
    },   
    
    


// WoC 

    41: {
      display() {
        let TMSunX = player.Sol.TMSun.x
        let TMSunPend = player.Sol.TMSun.pending

        let TMSPT = (TMSunPend.gte(1) || TMSunX.gte(1)) && player.Sol.selected == "TMSun"  ? `Difficulty: ${TMSunPend.plus(TMSunX)} / 5` : ``

        return `<h2>The Melted Sun </h2> 
        
        ${TMSPT}
        `
      },
      onClick() {  player.Sol.selected = "TMSun" },
      canClick() {return player.Sol.selected == ""},
      style() {return {
        "width": "140px",
        "height": "20px",
         "margin": "5px"
        }},  
        unlocked() {
          let TMSun = player.Sol.TMSun.x
          let TRMoon = player.Sol.TRMoon.x
          let TBSun = player.Sol.TBSun.x
          let TBCore = player.Sol.TBCore.x 
          
          let notForceHide = true
          if (TBCore.eq(2) && (TMSun.gte(2) && TRMoon.gte(3) && TBSun.gte(2) )) notForceHide = false
          else if (TBCore.eq(1) && (TMSun.gte(1) && TRMoon.gte(1) && TBSun.gte(1) ) ) notForceHide = false
  
          return player.Sol.sub == "WoC" && notForceHide && !(player.Sol.selected == "TRMoon" || player.Sol.selected == "TBSun")
        
        }
    },


    42: {
      display() {
        
        
        let TRMoonX = player.Sol.TRMoon.x
        let TRMoonPend = player.Sol.TRMoon.pending

        let TRMPT = (TRMoonPend.gte(1) || TRMoonX.gte(1)) && player.Sol.selected == "TRMoon" ? `Difficulty: ${TRMoonPend.plus(TRMoonX)} / 5` : ``

       return `<h2>The Raging Moon</h2>
        
        ${TRMPT}
        `
        
        },
      onClick() {  player.Sol.selected = "TRMoon"    },
      canClick() {return player.Sol.selected == ""},
      style() {return {
        "width": "133px",
        "height": "20px",
         "margin": "5px"
        }},  
        unlocked() {
          let TMSun = player.Sol.TMSun.x
          let TRMoon = player.Sol.TRMoon.x
          let TBSun = player.Sol.TBSun.x
          let TBCore = player.Sol.TBCore.x 
          
          let notForceHide = true
          if (TBCore.eq(2) && (TMSun.gte(2) && TRMoon.gte(3) && TBSun.gte(2) )) notForceHide = false
          else if (TBCore.eq(1) && (TMSun.gte(1) && TRMoon.gte(1) && TBSun.gte(1) ) ) notForceHide = false
  
          return player.Sol.sub == "WoC" && notForceHide && !(player.Sol.selected == "TBSun" || player.Sol.selected == "TMSun")
        
        }
    },

    43: {
      display() {
        let TBSunX = player.Sol.TBSun.x
        let TBSunPend = player.Sol.TBSun.pending

        let TBSPT = (TBSunPend.gte(1) || TBSunX.gte(1)) && player.Sol.selected == "TBSun" ? `Difficulty: ${TBSunPend.plus(TBSunX)} / 5` : ``

        return `<h2> The Bleeding Eclipse </h2> 
        
        ${TBSPT}
        `
      
      },
      onClick() { 
       
        player.Sol.selected = "TBSun"; 
        // player.Sol.TBSun.pending = player.Sol.TBSun.x

       },
      canClick() {return player.Sol.selected == ""},
      style() {return {
        "width": "133px",
        "height": "20px",
        "margin": "5px"
        }},  
      unlocked() {
        let TMSun = player.Sol.TMSun.x
        let TRMoon = player.Sol.TRMoon.x
        let TBSun = player.Sol.TBSun.x
        let TBCore = player.Sol.TBCore.x 

        let notForceHide = true
        if (TBCore.eq(2) && (TMSun.gte(2) && TRMoon.gte(3) && TBSun.gte(2) )) notForceHide = false
        else if (TBCore.eq(1) && (TMSun.gte(1) && TRMoon.gte(1) && TBSun.gte(1) ) ) notForceHide = false

        return player.Sol.sub == "WoC" && notForceHide && !(player.Sol.selected == "TRMoon" || player.Sol.selected == "TMSun")
      
      }
    },
    
    // The broken core 
    44: {
      display() {return `<h2>The Broken Core</h2>`},
      onClick() {  player.Sol.selected = "TBC" },
      canClick() {
        let TBCore = player.Sol.TBCore.x
        return (TBCore.neq(3)) 
      },
      style() {return {
        "width": "100px",
        "height": "20px",
        "margin": "5px"
        }},  
      unlocked() {
        let TMSun = player.Sol.TMSun.x
        let TRMoon = player.Sol.TRMoon.x
        let TBSun = player.Sol.TBSun.x
        let TBCore = player.Sol.TBCore.x 


        let hasRequirements = false

        if (TBCore.eq(3)) hasRequirements = true
        if (TBCore.eq(2) && (TMSun.gte(2) && TRMoon.gte(3) && TBSun.gte(2) )) hasRequirements = true
        else if (TBCore.eq(1) && (TMSun.gte(1) && TRMoon.gte(1) && TBSun.gte(1) ) ) hasRequirements = true



        return player.Sol.sub == "WoC" && hasRequirements
      
      }
    },

    1111: {    
      display() {return `Respawn to redo this Check (Adds 1 to deaths) <br>
        <br> For the pressure overcame me...
        `},
      onClick() {EclipsiumReset();  player.Sol.activeCheck = ""; player.Sol.HelioRadiation = new Decimal(1); player.deaths += 1; switchTheme("Eclipse"); window.location.reload(); },
      canClick() {return true},
      style() {return {
        "width": "190px",
        "height": "80px",
        }},  
      unlocked() {return player.Sol.activeCheck == "Heliosphere" && player.Sol.HelioRadiation.gte(1e30)
        }
    
    },
    99: {
     
        display() {return `redo this duality (useful for Solarify)`},
        onClick() {EclipsiumReset(); player.L.Light = new Decimal(0); player.L.Dark = new Decimal(0); },
        canClick() {return true},
        style() {return {
          "width": "190px",
          "height": "40px",
          }},  
        unlocked() {return player.C.CenterPoints.gte(1) && getClickableState("L", this.id)}
      
    }

  },  
  

  // if (player["GL"].Solar_shards.gte(1))
    tooltip: () => `<p>Open Solaris, side layer <br>(last unlock of v0.6 17F-15B)</p>`,


          
           
   
    row: 2, 
    position: 3, 
    branches: ["E"],
    layerShown(){ 
      if ( hasMilestone("E",6) ) return true; else return false; 
    },

    unlocked(){
      return true
    },

  })